name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    ## USING BOT ACCOUNT - Bot expires in n days
    - name: Log in registry using robot
      run:  echo '${{ secrets.NCSA_ROBOT_PASSWORD }}' | docker login hub.ncsa.illinois.edu -u '${{ secrets.NCSA_ROBOT }}' --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hub.ncsa.illinois.edu/dsrs-fs/test-repo
      #run: docker build . --file Dockerfile --tag hub.ncsa.illinois.edu/dsrs-fs/test-repo:$(date +%s)
      #### this tag does not work?? this part specifically: $(date +%s)

    #- name: Log into the registry
    #  run: docker login hub.ncsa.illinois.edu --username ${{ secrets.NCSA_USERNAME }} --password ${{ secrets.NCSA_TOKEN }}
    
    - name: Push the Docker image
      run: docker push hub.ncsa.illinois.edu/dsrs-fs/test-repo
      #run: docker push hub.ncsa.illinois.edu/dsrs-fs/test-repo:$(date +%s)
      
  
  pull_and_run:
    needs: build_and_push ### This job will only run if the previous job is successful.
    ### Could be done in parallel, only doing it this way to get the latest image (produced by the previous job).
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
  
      # - name: Install ngrok
      #   # run: |
      #   #   wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
      #   #   unzip ngrok-stable-linux-amd64.zip
      #   #   ./ngrok version
      #   run: docker pull ngrok/ngrok

      # - name: Run ngrok
      #   run: docker run -e NGROK_AUTHTOKEN=${{ secrets.NGROK_TOKEN }} ngrok/ngrok http 3000

      # - name: Log in NGROK
      #   run: ngrok authtoken ${{ secrets.NGROK_TOKEN }}
  
      # - name: Run ngrok
      #   run: ngrok http 3000

      - name: Log into the registry
        run: docker login hub.ncsa.illinois.edu --username ${{ secrets.NCSA_USERNAME }} --password ${{ secrets.NCSA_TOKEN }}

      - name: Pull the Docker image
        run: docker pull hub.ncsa.illinois.edu/dsrs-fs/test-repo

      - name: Run the Docker image
        run: docker run --detach --publish 3000:80 hub.ncsa.illinois.edu/dsrs-fs/test-repo
        
