name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hub.ncsa.illinois.edu/dsrs-fs/test-repo
      #run: docker build . --file Dockerfile --tag hub.ncsa.illinois.edu/dsrs-fs/test-repo:$(date +%s)
      #### this tag does not work?? this part specifically: $(date +%s)

    - name: Log into the registry
      run: docker login hub.ncsa.illinois.edu --username ${{ secrets.NCSA_USERNAME }} --password ${{ secrets.NCSA_TOKEN }}

    - name: Push the Docker image
      run: docker push hub.ncsa.illinois.edu/dsrs-fs/test-repo
      #run: docker push hub.ncsa.illinois.edu/dsrs-fs/test-repo:$(date +%s)
  
  pull_and_run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Log into the registry
      run: docker login hub.ncsa.illinois.edu --username ${{ secrets.NCSA_USERNAME }} --password ${{ secrets.NCSA_TOKEN }}

    - name: Pull the Docker image
      run: docker pull hub.ncsa.illinois.edu/dsrs-fs/test-repo

    - name: Run the Docker image
      run: docker run --detach --publish 3000:80 hub.ncsa.illinois.edu/dsrs-fs/test-repo

    - name: Expose the Docker image using ngrok
      run: ngrok http 3000
      